### ISSUE TITLE
RBSE Integration Error

### ISSUE THREAD

**Issue by Kiara-Liam** [AbraxasWorks/Medical-System-Expansion---Revived#37]
RBSE (and probably others as well) install their arm prothethics in the shoulder slot, resulting in a shoulder implant, while the arm itself is still missing (and can not be replaced).

I will take a look at it

**Comment by JonM0** [comment]
In vanilla arm prostheses are installed in the shoulder slot, I added a forearm implant for the arm slot.

**Comment by Kiara-Liam** [comment]
Stupid me agian. Didn't update my local fork. But it was a nice effect, the arm was correctly installed in the shoulder, the arm was still missing and it spawned in a perfectly usable forearm, hand and five finger implants XD
